image: Visual Studio 2017

install:
  - git submodule update --init

environment:
  SDL2_ZIP: SDL2-devel-2.0.5-VC.zip
  SDL2_DOWNLOAD_DIR: c:\sdl2
  SDL2_ROOT_DIR: c:\sdl2\SDL2-2.0.5
  matrix:
    - GENERATOR: Visual Studio 15 2017
      CONFIG: Release
      DEPLOY: true
      DEPLOY_NAME: binjgb-win32.zip
      SDL_DLL_PATH: lib\x86\SDL2.dll
    - GENERATOR: Visual Studio 15 2017 Win64
      CONFIG: Debug
      DEPLOY: false
      DEPLOY_NAME: binjgb-win64.zip
      SDL_DLL_PATH: lib\x64\SDL2.dll
    - GENERATOR: Visual Studio 15 2017 Win64
      CONFIG: Release
      DEPLOY: true
      DEPLOY_NAME: binjgb-win64.zip
      SDL_DLL_PATH: lib\x64\SDL2.dll

build_script:
  - cmake --version
  - mkdir %SDL2_DOWNLOAD_DIR%
  - cd %SDL2_DOWNLOAD_DIR%
  - appveyor DownloadFile https://www.libsdl.org/release/%SDL2_ZIP%
  - 7z x %SDL2_ZIP% > nul
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake .  -G "%GENERATOR%" -DSDL2_ROOT_DIR=%SDL2_ROOT_DIR% -DCMAKE_BUILD_TYPE=%CONFIG%
  - cmake --build . --config %CONFIG%

after_build:
  - 7z a %DEPLOY_NAME% %APPVEYOR_BUILD_FOLDER%\%CONFIG%\binjgb*.exe %SDL2_ROOT_DIR%\%SDL_DLL_PATH%

artifacts:
  - path: "%DEPLOY_NAME%"
    name: binjgb

deploy:
  description: 'binjgb release'
  provider: GitHub
  auth_token:
    secure: cwu4/slBKTWp4az+lK6uJ8F0Wk2RGW0EehDZ+zr8GX/AeJUEPsJ+ctOdvtROUF7v
  artifact: "%DEPLOY_NAME%"
  on:
    appveyor_repo_tag: true
    deploy: true
